import type { ApiRealisation } from "@/lib/api/types";

const currentYear = new Date().toISOString();

export const realisationFilters = [
  { id: "all", label: "Tous" },
  { id: "topography", label: "Topographie" },
  { id: "geodesy", label: "GNSS & Géodésie" },
  { id: "gis", label: "Cartographie SIG" },
  { id: "architecture", label: "Architecture" },
  { id: "equipment", label: "Équipements" },
] as const;

export type RealisationCategory = Exclude<(typeof realisationFilters)[number]["id"], "all">;
export type RealisationFilter = (typeof realisationFilters)[number]["id"];

function item(
  index: number,
  data: {
    slug: string;
    category: RealisationCategory;
    categoryLabel: string;
    year: number;
    surfaceValue: number;
    surface: string;
    title: string;
    location: string;
    metrics: [string, string][];
    tags: string[];
    color: string;
    description: string;
    features: string[];
    featured?: boolean;
    result?: string;
  },
): ApiRealisation {
  return {
    id: `fallback-${index}`,
    title: data.title,
    slug: data.slug,
    category: data.category,
    categoryLabel: data.categoryLabel,
    year: data.year,
    client: "",
    location: data.location,
    completionDate: `${data.year}-01-01T00:00:00.000Z`,
    imageUrl: "",
    gallery: [],
    description: data.description,
    surface: data.surface,
    surfaceValue: data.surfaceValue,
    levels: "",
    budget: "",
    result: data.result || data.metrics[2]?.[1] || "",
    color: data.color,
    servicesUsed: [data.categoryLabel],
    technicalTags: data.tags,
    features: data.features,
    published: true,
    featured: Boolean(data.featured),
    displayOrder: index + 1,
    metaTitle: data.title,
    metaDescription: data.description,
    deletedAt: null,
    createdAt: currentYear,
    updatedAt: currentYear,
    metrics: data.metrics.map(([label, value], metricIndex) => ({
      label,
      value,
      displayOrder: metricIndex + 1,
    })),
  };
}

export const defaultRealisations: ApiRealisation[] = [
  item(0, {
    slug: "leve-topographique-zone-industrielle-bonaberi",
    category: "topography",
    categoryLabel: "Topographie",
    year: 2024,
    surfaceValue: 420,
    surface: "420 ha",
    title: "Levé topographique - Zone industrielle de Bonabéri",
    location: "Douala",
    metrics: [["Surface", "420 ha"], ["Mission", "Levé complet"], ["Résultat", "Livré"]],
    tags: ["Drone", "GPS RTK"],
    color: "#1E3A64",
    description: "Levé topographique complet d'une zone industrielle de 420 hectares à Douala, réalisé par drone et GPS RTK.",
    features: ["Drone", "GPS RTK", "Levé complet", "Mission livrée"],
    featured: true,
    result: "Mission livrée",
  }),
  item(1, {
    slug: "implantation-immeuble-r8",
    category: "topography",
    categoryLabel: "Topographie",
    year: 2024,
    surfaceValue: 1.8,
    surface: "1,8 ha",
    title: "Implantation d'un immeuble R+8",
    location: "Douala",
    metrics: [["Surface", "1,8 ha"], ["Mission", "Implantation"], ["Résultat", "Précision ±2 cm"]],
    tags: ["Implantation", "Station totale"],
    color: "#162F52",
    description: "Implantation topographique d'un immeuble R+8 sur une surface de 1,8 hectare avec une précision de ±2 cm.",
    features: ["Implantation", "Station totale", "Précision ±2 cm"],
  }),
  item(2, {
    slug: "reseau-geodesique-communal",
    category: "geodesy",
    categoryLabel: "GNSS & Géodésie",
    year: 2023,
    surfaceValue: 125,
    surface: "125 points",
    title: "Réseau géodésique communal",
    location: "Yaoundé",
    metrics: [["Points", "125"], ["Mission", "GNSS"], ["Résultat", "Validé"]],
    tags: ["GNSS", "Réseau"],
    color: "#1C3560",
    description: "Mise en place et validation d'un réseau géodésique communal composé de 125 points GNSS à Yaoundé.",
    features: ["GNSS", "Réseau", "125 points", "Mission validée"],
  }),
  item(3, {
    slug: "cartographie-sig-commune",
    category: "gis",
    categoryLabel: "Cartographie SIG",
    year: 2023,
    surfaceValue: 180,
    surface: "180 km²",
    title: "Cartographie SIG d'une commune",
    location: "Kribi",
    metrics: [["Surface", "180 km²"], ["Mission", "SIG"], ["Résultat", "Base livrée"]],
    tags: ["SIG", "QGIS"],
    color: "#0F2A4A",
    description: "Cartographie SIG d'une commune couvrant 180 km² à Kribi, avec constitution et livraison de la base de données.",
    features: ["SIG", "QGIS", "Base de données", "180 km²"],
  }),
  item(4, {
    slug: "lotissement-residentiel",
    category: "topography",
    categoryLabel: "Topographie",
    year: 2023,
    surfaceValue: 55,
    surface: "55 ha",
    title: "Lotissement résidentiel",
    location: "Douala",
    metrics: [["Surface", "55 ha"], ["Mission", "Bornage"], ["Résultat", "Plans livrés"]],
    tags: ["Bornage", "Cadastre"],
    color: "#182E50",
    description: "Mission de bornage d'un lotissement résidentiel de 55 hectares à Douala, avec production des plans cadastraux.",
    features: ["Bornage", "Cadastre", "55 ha", "Plans livrés"],
  }),
  item(5, {
    slug: "plans-complexe-scolaire",
    category: "architecture",
    categoryLabel: "Architecture",
    year: 2023,
    surfaceValue: 4800,
    surface: "4 800 m²",
    title: "Plans d'un complexe scolaire",
    location: "Douala",
    metrics: [["Surface", "4 800 m²"], ["Mission", "Architecture"], ["Résultat", "Permis préparé"]],
    tags: ["Plans", "Permis"],
    color: "#112440",
    description: "Conception des plans architecturaux d'un complexe scolaire de 4 800 m² et préparation du dossier de permis.",
    features: ["Plans", "Permis", "Architecture", "4 800 m²"],
  }),
  item(6, {
    slug: "cartographie-reseaux-eau",
    category: "gis",
    categoryLabel: "Cartographie SIG",
    year: 2022,
    surfaceValue: 48,
    surface: "48 km",
    title: "Cartographie des réseaux d'eau",
    location: "Douala",
    metrics: [["Réseau", "48 km"], ["Mission", "SIG"], ["Résultat", "Données structurées"]],
    tags: ["AEP", "SIG"],
    color: "#0D2240",
    description: "Cartographie SIG de 48 km de réseaux d'eau à Douala et structuration des données géospatiales associées.",
    features: ["AEP", "SIG", "48 km", "Données structurées"],
  }),
  item(7, {
    slug: "etude-corridor-routier",
    category: "topography",
    categoryLabel: "Topographie",
    year: 2022,
    surfaceValue: 32,
    surface: "32 km",
    title: "Étude corridor routier",
    location: "Bafoussam",
    metrics: [["Distance", "32 km"], ["Mission", "Levé"], ["Résultat", "Profil livré"]],
    tags: ["Route", "Levé"],
    color: "#1A3260",
    description: "Levé topographique d'un corridor routier de 32 km à Bafoussam avec production du profil demandé.",
    features: ["Route", "Levé", "32 km", "Profil livré"],
  }),
  item(8, {
    slug: "location-gps-rtk",
    category: "equipment",
    categoryLabel: "Équipements",
    year: 2022,
    surfaceValue: 6,
    surface: "6 mois",
    title: "Location GPS RTK",
    location: "Douala",
    metrics: [["Durée", "6 mois"], ["Mission", "Location"], ["Résultat", "Matériel disponible"]],
    tags: ["GPS", "RTK"],
    color: "#0E2442",
    description: "Mise à disposition d'un équipement GPS RTK à Douala pour une période de six mois.",
    features: ["GPS", "RTK", "Location", "6 mois"],
  }),
  item(9, {
    slug: "implantation-pylones-telecom",
    category: "geodesy",
    categoryLabel: "GNSS & Géodésie",
    year: 2021,
    surfaceValue: 34,
    surface: "34 sites",
    title: "Implantation pylônes télécom",
    location: "Garoua",
    metrics: [["Sites", "34"], ["Mission", "GNSS"], ["Résultat", "Points validés"]],
    tags: ["Télécom", "RTK"],
    color: "#102036",
    description: "Implantation GNSS de pylônes télécom sur 34 sites à Garoua avec validation des points RTK.",
    features: ["Télécom", "RTK", "34 sites", "Points validés"],
  }),
  item(10, {
    slug: "etude-batiment-administratif",
    category: "architecture",
    categoryLabel: "Architecture",
    year: 2021,
    surfaceValue: 6500,
    surface: "6 500 m²",
    title: "Étude d'un bâtiment administratif",
    location: "Douala",
    metrics: [["Surface", "6 500 m²"], ["Mission", "Étude"], ["Résultat", "Dossier livré"]],
    tags: ["Architecture", "BIM"],
    color: "#13253E",
    description: "Étude architecturale et technique d'un bâtiment administratif de 6 500 m² à Douala avec dossier BIM livré.",
    features: ["Architecture", "BIM", "6 500 m²", "Dossier livré"],
  }),
  item(11, {
    slug: "sig-agricole",
    category: "gis",
    categoryLabel: "Cartographie SIG",
    year: 2021,
    surfaceValue: 720,
    surface: "720 ha",
    title: "SIG agricole",
    location: "Bafoussam",
    metrics: [["Surface", "720 ha"], ["Mission", "SIG"], ["Résultat", "Cartes livrées"]],
    tags: ["Agriculture", "SIG"],
    color: "#192E54",
    description: "Développement d'un SIG agricole couvrant 720 hectares à Bafoussam avec production des cartes thématiques.",
    features: ["Agriculture", "SIG", "720 ha", "Cartes livrées"],
  }),
  item(12, {
    slug: "bornage-foncier",
    category: "topography",
    categoryLabel: "Topographie",
    year: 2020,
    surfaceValue: 285,
    surface: "285 parcelles",
    title: "Bornage foncier",
    location: "Yaoundé",
    metrics: [["Parcelles", "285"], ["Mission", "Cadastre"], ["Résultat", "Bornes posées"]],
    tags: ["Bornage", "Cadastre"],
    color: "#142848",
    description: "Mission cadastrale de bornage foncier portant sur 285 parcelles à Yaoundé avec pose des bornes.",
    features: ["Bornage", "Cadastre", "285 parcelles", "Bornes posées"],
  }),
  item(13, {
    slug: "controle-geodesique-barrage",
    category: "geodesy",
    categoryLabel: "GNSS & Géodésie",
    year: 2020,
    surfaceValue: 92,
    surface: "92 points",
    title: "Contrôle géodésique barrage",
    location: "Lom Pangar",
    metrics: [["Points", "92"], ["Mission", "Contrôle"], ["Résultat", "Contrôle validé"]],
    tags: ["GNSS", "Contrôle"],
    color: "#0C1E38",
    description: "Contrôle géodésique de 92 points sur le barrage de Lom Pangar avec validation des mesures GNSS.",
    features: ["GNSS", "Contrôle", "92 points", "Contrôle validé"],
  }),
  item(14, {
    slug: "location-station-totale-leica",
    category: "equipment",
    categoryLabel: "Équipements",
    year: 2019,
    surfaceValue: 3,
    surface: "3 mois",
    title: "Location Station Totale Leica",
    location: "Douala",
    metrics: [["Durée", "3 mois"], ["Mission", "Location"], ["Résultat", "Équipement loué"]],
    tags: ["Leica", "Station totale"],
    color: "#172C50",
    description: "Location d'une station totale Leica à Douala pour une mission professionnelle d'une durée de trois mois.",
    features: ["Leica", "Station totale", "Location", "3 mois"],
  }),
];

export function sortRealisations<T extends { displayOrder?: number | null; createdAt?: string }>(items: T[]) {
  return [...items].sort((a, b) => (a.displayOrder ?? 0) - (b.displayOrder ?? 0));
}
