import type { ApiService, ServicePageSettings } from "@/lib/api/types";

export const servicePageDefaults: ServicePageSettings = {
  hero: {
    eyebrow: "NOS PRESTATIONS",
    titleBeforeHighlight: "Des solutions",
    highlightedTitle: "techniques",
    titleAfterHighlight: "pour tous vos projets",
    description:
      "Topographie, géodésie GNSS, cartographie SIG, architecture, implantation et location d'équipements professionnels.",
  },
  stats: [
    { value: "120+", label: "LEVÉS RÉALISÉS" },
    { value: "15 ans", label: "ANS D'EXPÉRIENCE" },
    { value: "6", label: "DOMAINES TECHNIQUES" },
    { value: "48h", label: "DE RÉPONSE" },
  ],
};

export const defaultServices: ApiService[] = [
  {
    title: "Levés topographiques et implantation terrain",
    slug: "topographie",
    description:
      "Mesures de terrain, implantations, nivellement et plans topographiques pour projets de construction et d'aménagement.",
    longDescription:
      "Levés planimétriques et altimétriques, implantation d'ouvrages, nivellement de précision et plans détaillés.",
    category: "TOPO",
    tabId: "TOPO",
    tabLabel: "TOPOGRAPHIE",
    eyebrow: "TOPOGRAPHIE & GÉOMATIQUE",
    heroTitle: "Levés topographiques\net implantation terrain",
    featuredLabel: "PRESTATION PRINCIPALE",
    featuredTitle: "Levés topographiques\nprofessionnels",
    featuredCtaLabel: "Demander un devis",
    featuredCtaHref: "/contact",
    processTitle: "Notre processus d'acquisition",
    faqTitle: "Questions fréquentes - Immobilier",
    ctaTitle: "Besoin d'une expertise\npour votre projet ?",
    ctaSubtitle: "Topographie • GNSS • Cartographie • Architecture • Équipements",
    ctaLabel: "Demander un devis",
    ctaHref: "/contact",
    priceTableHeaders: [],
    showTestimonials: true,
    showEngagements: false,
    icon: "Home",
    imageUrl: "",
    gallery: [],
    displayOrder: 1,
    published: true,
    cards: [
      { icon: "Home", title: "Levés Topographiques", description: "Mesures de terrain, implantations, nivellement et plans topographiques.", tags: ["Terrain", "Implantation", "Nivellement"], displayOrder: 1 },
      { icon: "KeyRound", title: "Géodésie & GNSS", description: "Levés GNSS RTK, géoréférencement et contrôle de précision.", tags: ["RTK", "GNSS", "Géoréférencement"], displayOrder: 2 },
      { icon: "Store", title: "Cartographie & SIG", description: "Production de cartes numériques, analyse spatiale et bases de données.", tags: ["SIG", "Cartes", "Analyse"], displayOrder: 3 },
      { icon: "Building2", title: "Architecture & Études", description: "Plans architecturaux, études techniques et faisabilité.", tags: ["Plans", "Études", "Architecture"], displayOrder: 4 },
      { icon: "MapPin", title: "Implantation & VRD", description: "Implantation d'ouvrages, voiries et réseaux divers.", tags: ["VRD", "Chantier", "Implantation"], displayOrder: 5 },
      { icon: "Star", title: "Location d'Équipements", description: "Drone, GNSS, stations totales et matériel terrain.", tags: ["Drone", "GNSS", "Station Totale"], displayOrder: 6 },
    ],
    features: [
      { text: "Levés GNSS RTK de haute précision", displayOrder: 1 },
      { text: "Implantation de bâtiments et infrastructures", displayOrder: 2 },
      { text: "Nivellement de chantier", displayOrder: 3 },
      { text: "Plans topographiques détaillés", displayOrder: 4 },
      { text: "Contrôle et suivi d'exécution", displayOrder: 5 },
    ],
    processSteps: [
      { number: "1", firstLine: "Analyse", secondLine: "de besoins", displayOrder: 1 },
      { number: "2", firstLine: "Reconnaissance", secondLine: "terrain", displayOrder: 2 },
      { number: "3", firstLine: "Acquisition", secondLine: "des données", displayOrder: 3 },
      { number: "4", firstLine: "Traitement &", secondLine: "contrôle", displayOrder: 4 },
      { number: "5", firstLine: "Livraison des", secondLine: "résultats", displayOrder: 5 },
    ],
    faqs: [
      { question: "Qu'est-ce qu'un levé topographique ?", answer: "Un levé topographique permet de relever avec précision les caractéristiques d'un terrain avant un projet de construction.", displayOrder: 1 },
      { question: "Quelle précision obtenez-vous avec le GNSS RTK ?", answer: "La technologie RTK permet une précision centimétrique.", displayOrder: 2 },
      { question: "Proposez-vous la location d'équipements ?", answer: "Oui. Nous proposons drones, récepteurs GNSS et stations totales.", displayOrder: 3 },
    ],
    pricingPlans: [],
    pricingRows: [],
    testimonials: [
      { quote: "PIE a réalisé nos levés topographiques avec une excellente précision et dans les délais annoncés.", name: "Christelle Mbarga", role: "Acheteuse - Résidentiel", displayOrder: 1 },
      { quote: "Leur expertise GNSS RTK nous a permis d'obtenir des résultats fiables pour notre chantier.", name: "Robert Tagne", role: "Investisseur - Commercial", displayOrder: 2 },
    ],
    engagements: [],
  },
  {
    title: "Géodésie & Positionnement GNSS",
    slug: "gnss-geodesie",
    description:
      "Levés GNSS RTK, géoréférencement, densification de réseaux géodésiques et contrôle de précision pour tous vos projets.",
    longDescription:
      "Mesures GNSS centimétriques, géoréférencement de projets, implantation et contrôle géodésique.",
    category: "GNSS & GÉODÉSIE",
    tabId: "GNSS",
    tabLabel: "GNSS & GÉODÉSIE",
    eyebrow: "GNSS & GÉODÉSIE",
    heroTitle: "Géodésie &\nPositionnement GNSS",
    featuredLabel: "PRESTATION PRINCIPALE",
    featuredTitle: "Levés GNSS RTK\nde haute précision",
    featuredCtaLabel: "Demander un devis",
    featuredCtaHref: "/contact",
    processTitle: "NOTRE PROCESSUS GNSS",
    faqTitle: "Questions fréquentes - Ingénierie",
    ctaTitle: "Besoin d'une expertise\npour votre projet ?",
    ctaSubtitle: "Topographie • GNSS • Cartographie • Architecture • Équipements",
    ctaLabel: "Demander un devis",
    ctaHref: "/contact",
    priceTableHeaders: [],
    showTestimonials: false,
    showEngagements: true,
    icon: "Ruler",
    imageUrl: "",
    gallery: [],
    displayOrder: 2,
    published: true,
    cards: [
      { icon: "Hammer", title: "Levés GNSS RTK", description: "Acquisition de données GNSS avec précision centimétrique pour projets techniques.", tags: ["RTK", "GNSS", "Précision"], displayOrder: 1 },
      { icon: "Ruler", title: "Géoréférencement", description: "Référencement précis de terrains, ouvrages et infrastructures.", tags: ["Coordonnées", "SIG", "Référentiel"], displayOrder: 2 },
      { icon: "Building2", title: "Points de contrôle", description: "Installation et contrôle de repères géodésiques pour vos projets.", tags: ["Repères", "Contrôle", "Mesures"], displayOrder: 3 },
      { icon: "Building2", title: "Densification géodésique", description: "Extension de réseaux géodésiques pour zones d'aménagement.", tags: ["Réseau", "Géodésie", "Précision"], displayOrder: 4 },
      { icon: "Eye", title: "Implantation GNSS", description: "Implantation d'ouvrages, axes et points de chantier.", tags: ["Implantation", "Chantier", "GNSS"], displayOrder: 5 },
      { icon: "Plug", title: "Contrôle qualité", description: "Vérification des données, contrôle et validation des relevés.", tags: ["Contrôle", "Validation", "Qualité"], displayOrder: 6 },
    ],
    features: [
      { text: "Précision centimétrique RTK", displayOrder: 1 },
      { text: "Géoréférencement de projets", displayOrder: 2 },
      { text: "Mise en place de points de contrôle", displayOrder: 3 },
      { text: "Densification géodésique", displayOrder: 4 },
      { text: "Contrôle de précision et vérification", displayOrder: 5 },
    ],
    processSteps: [
      { number: "1", firstLine: "Analyse du", secondLine: "besoin", displayOrder: 1 },
      { number: "2", firstLine: "Préparation", secondLine: "terrain", displayOrder: 2 },
      { number: "3", firstLine: "Acquisition", secondLine: "GNSS", displayOrder: 3 },
      { number: "4", firstLine: "Traitement", secondLine: "des données", displayOrder: 4 },
      { number: "5", firstLine: "Livraison", secondLine: "des résultats", displayOrder: 5 },
    ],
    faqs: [
      { question: "Quelle précision obtenez-vous avec le GNSS RTK ?", answer: "Nos levés GNSS RTK atteignent généralement une précision centimétrique selon les conditions du terrain.", displayOrder: 1 },
      { question: "Intervenez-vous partout au Cameroun ?", answer: "Oui, nos équipes interviennent à Douala, Yaoundé et dans toutes les régions du Cameroun.", displayOrder: 2 },
      { question: "Les données sont-elles compatibles avec AutoCAD et SIG ?", answer: "Oui, les données peuvent être livrées dans des formats compatibles AutoCAD, SIG et autres logiciels techniques.", displayOrder: 3 },
    ],
    pricingPlans: [],
    pricingRows: [],
    testimonials: [],
    engagements: [
      { icon: "ShieldCheck", title: "Précision RTK", description: "Précision centimétrique garantie sur les relevés.", displayOrder: 1 },
      { icon: "CalendarDays", title: "Rapidité d'exécution", description: "Acquisition rapide des données terrain.", displayOrder: 2 },
      { icon: "BarChart3", title: "Compatibilité SIG", description: "Export compatible SIG, DAO et BIM.", displayOrder: 3 },
      { icon: "Check", title: "Fiabilité des données", description: "Contrôle qualité avant livraison.", displayOrder: 4 },
    ],
  },
  {
    title: "Cartographie SIG et analyse spatiale",
    slug: "cartographie-sig",
    description:
      "Valorisation et analyse de vos données spatiales. Production de cartes numériques, analyses SIG et gestion de bases de données géographiques.",
    category: "CARTOGRAPHIE",
    tabId: "CARTOGRAPHIE",
    tabLabel: "CARTOGRAPHIE SIG",
    eyebrow: "PÔLE CARTOGRAPHIE",
    heroTitle: "Cartographie SIG",
    heroHighlight: "et analyse spatiale",
    ctaTitle: "Besoin d'une expertise\npour votre projet ?",
    ctaSubtitle: "Topographie • GNSS • Cartographie • Architecture • Équipements",
    ctaLabel: "Demander un devis",
    ctaHref: "/contact",
    priceTableHeaders: [],
    icon: "KeyRound",
    imageUrl: "",
    gallery: [],
    displayOrder: 3,
    published: true,
    cards: [
      { icon: "Users", title: "Cartographie numérique", description: "Création de cartes numériques professionnelles pour projets, études et aménagements.", tags: ["SIG", "Cartes", "Numérique"], displayOrder: 1 },
      { icon: "Banknote", title: "Analyse spatiale", description: "Traitement et analyse des données géographiques pour faciliter la prise de décision.", tags: ["Analyse", "Données", "Territoire"], displayOrder: 2 },
      { icon: "Wrench", title: "Cartographie thématique", description: "Production de cartes spécialisées : urbanisme, environnement, infrastructures et réseaux.", tags: ["Thématique", "Urbanisme", "Réseaux"], displayOrder: 3 },
      { icon: "FileText", title: "Bases de données SIG", description: "Conception et structuration de bases de données géographiques performantes.", tags: ["Base SIG", "Données", "GIS"], displayOrder: 4 },
      { icon: "BarChart3", title: "Mise à jour géospatiale", description: "Actualisation et maintenance des données géographiques de vos projets.", tags: ["Mise à jour", "Données", "Suivi"], displayOrder: 5 },
      { icon: "ShieldCheck", title: "Visualisation & reporting", description: "Présentation claire des données spatiales sous forme de cartes et tableaux d'analyse.", tags: ["Rapports", "Cartes", "Décision"], displayOrder: 6 },
    ],
    features: [],
    processSteps: [],
    faqs: [],
    pricingPlans: [
      { name: "CARTOGRAPHIE", price: "6%", note: "Cartes de base pour projets simples.", features: ["Cartographie numérique", "Export PDF", "Géoréférencement", "Livraison rapide"], featured: false, displayOrder: 1 },
      { name: "SIG AVANCÉ", price: "9%", note: "Analyses spatiales avancées et solutions géomatiques pour projets professionnels.", features: ["Tout Cartographie inclus", "Analyse spatiale", "Base de données SIG", "Cartes thématiques", "Rapport technique"], featured: true, displayOrder: 2 },
      { name: "PROJET SUR MESURE", price: "Sur devis", note: "Accompagnement complet pour projets complexes et grands territoires.", features: ["Études complexes", "Grand territoire", "Données multi-sources", "Accompagnement complet", "Support technique"], featured: false, displayOrder: 3 },
    ],
    pricingRows: [],
    testimonials: [],
    engagements: [],
  },
  {
    title: "Architecture, études & conception",
    slug: "architecture",
    description:
      "Conception architecturale, études techniques et accompagnement administratif pour concrétiser vos projets de construction.",
    category: "ARCHITECTURE",
    tabId: "ARCHITECTURE",
    tabLabel: "ARCHITECTURE",
    eyebrow: "ARCHITECTURE",
    heroTitle: "Architecture, études &",
    heroHighlight: "conception",
    processTitle: "PROCESSUS ARCHITECTURAL",
    faqTitle: "Questions fréquentes - Conseil",
    ctaTitle: "Besoin d'une expertise\npour votre projet ?",
    ctaSubtitle: "Topographie • GNSS • Cartographie • Architecture • Équipements",
    ctaLabel: "Demander un devis",
    ctaHref: "/contact",
    priceTableHeaders: [],
    icon: "BadgeCheck",
    imageUrl: "",
    gallery: [],
    displayOrder: 4,
    published: true,
    cards: [
      { icon: "FileCheck", title: "Plans architecturaux", description: "Conception de plans de maisons, immeubles, commerces et bâtiments administratifs selon vos besoins.", tags: ["Plans", "Conception"], displayOrder: 1 },
      { icon: "BarChart3", title: "Études de faisabilité", description: "Analyse technique, financière et réglementaire pour évaluer la viabilité de votre projet avant son lancement.", tags: ["Faisabilité", "Rentabilité"], displayOrder: 2 },
      { icon: "BadgeCheck", title: "Permis de construire", description: "Préparation et dépôt des dossiers administratifs nécessaires à l'obtention du permis de construire.", tags: ["Urbanisme", "Dossier"], displayOrder: 3 },
      { icon: "Banknote", title: "Modélisation 3D", description: "Visualisation réaliste de votre futur bâtiment grâce à des maquettes et rendus architecturaux 3D.", tags: ["3D", "Rendu"], displayOrder: 4 },
      { icon: "Scale", title: "Suivi administratif", description: "Accompagnement auprès des administrations et organismes compétents durant tout le projet.", tags: ["Suivi", "Formalités"], displayOrder: 5 },
      { icon: "Plane", title: "Assistance projet", description: "Conseils techniques et coordination des différents intervenants pour garantir le bon déroulement du projet.", tags: ["Coordination", "Support"], displayOrder: 6 },
    ],
    features: [],
    processSteps: [
      { number: "1", firstLine: "Prise de", secondLine: "besoin", displayOrder: 1 },
      { number: "2", firstLine: "Étude &", secondLine: "conception", displayOrder: 2 },
      { number: "3", firstLine: "Plans &", secondLine: "validation", displayOrder: 3 },
      { number: "4", firstLine: "Permis &", secondLine: "formalités", displayOrder: 4 },
      { number: "5", firstLine: "Suivi du", secondLine: "projet", displayOrder: 5 },
    ],
    faqs: [
      { question: "Combien coûte un plan architectural ?", answer: "Le coût dépend de la superficie, du type de bâtiment et du niveau de détail demandé. Un devis personnalisé est établi après étude de votre projet.", displayOrder: 1 },
      { question: "Pouvez-vous obtenir le permis de construire pour moi ?", answer: "Oui. Nous pouvons constituer le dossier technique et vous accompagner dans les démarches administratives jusqu'à l'obtention du permis.", displayOrder: 2 },
    ],
    pricingPlans: [],
    pricingRows: [],
    testimonials: [],
    engagements: [],
  },
  {
    title: "Location d'équipements professionnels",
    slug: "location-equipements",
    description:
      "Louez du matériel topographique de haute précision pour vos levés, implantations, contrôles et travaux de terrain.",
    category: "LOCATION",
    tabId: "LOCATION",
    tabLabel: "LOCATION D'ÉQUIPEMENTS",
    eyebrow: "Location d'équipements",
    heroTitle: "Des équipements\nprofessionnels",
    heroHighlight: "à votre disposition",
    ctaTitle: "Need professional\nsurveying equipment?",
    ctaSubtitle: "Drone • GNSS RTK • CORS • Total Stations • Mapping",
    ctaLabel: "Demander un devis",
    ctaHref: "/contact",
    pricingNote:
      "Equipment availability depends on stock. A rental agreement and security deposit may be required depending on the selected equipment.",
    priceTableHeaders: ["Equipment", "Price", "Duration"],
    icon: "ReceiptText",
    imageUrl: "",
    gallery: [],
    displayOrder: 5,
    published: true,
    cards: [],
    features: [],
    processSteps: [],
    faqs: [],
    pricingPlans: [],
    pricingRows: [
      { item: "Drone DJI Mavic 3 Enterprise", price: "40 000 FCFA", duration: "Per day", highlighted: false, displayOrder: 1 },
      { item: "GNSS RTK Receiver Pair", price: "20 000 FCFA", duration: "Per day", highlighted: false, displayOrder: 2 },
      { item: "CORS GNSS Receiver", price: "10 000 FCFA", duration: "5 days", highlighted: false, displayOrder: 3 },
      { item: "Total Station", price: "Quotation", duration: "Per day", highlighted: false, displayOrder: 4 },
      { item: "Field Controller", price: "Included depending on equipment", duration: "Per day", highlighted: false, displayOrder: 5 },
      { item: "Specialized Software", price: "Quotation", duration: "Per project", highlighted: false, displayOrder: 6 },
      { item: "Technical Assistance", price: "Quotation", duration: "Per mission", highlighted: false, displayOrder: 7 },
      { item: "Reservation & Consultation", price: "FREE", duration: "Immediate", highlighted: true, displayOrder: 8 },
    ],
    testimonials: [],
    engagements: [],
  },
];

export function sortByDisplayOrder<T extends { displayOrder?: number | null; order?: number | null }>(items: T[]) {
  return [...items].sort((a, b) => (a.displayOrder ?? a.order ?? 0) - (b.displayOrder ?? b.order ?? 0));
}
